# Generated by Django 5.0.2 on 2024-03-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_remove_city_cityid_city_description_city_humidity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='gender',
        ),
    ]
