# Generated by Django 5.0.2 on 2024-04-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_remove_users_cities_users_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('forecast_date', models.DateField()),
                ('forecast_time', models.TimeField()),
                ('temperature', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
